#!/usr/bin/python
# Copyright @ 2012 Michael P. Reilly. All rights reserved.

from pyerector import *

# files to be including in packaging
packlist = ('pyerector.py', 'pyerector.pyc', 'setup.py', 'README', 'LICENSE')

class Cleantest(Target):
    """Clean the test directory."""
    tasks = (Remove(files=('testdir',)),)
class Realclean(Target):
    """Clean up the cruft (including pyc) files."""
    tasks = (Remove(files=('*.pyc',)),)
    dependencies = ('Clean',)
class Localtest(Target):
    """Ensure the packaging looks correct."""
    tasks = (
        Untar(root='testdir/tar', name='pyerector.tgz'),
        Unzip(root='testdir/zip', name='pyerector.zip'),
    )
    dependencies = ('InitDirs', 'Packaging',)

Test.dependencies = ('Localtest',) + Test.dependencies
Clean.files = ('pyerector.tgz', 'pyerector.zip', 'build', 'dist', 'MANIFEST')
Clean.dependencies = ('Cleantest',)
InitDirs.files = ('testdir/zip', 'testdir/tar')
Packaging.tasks = (
    Zip(name='pyerector.zip', files=packlist),
    Tar(name='pyerector.tgz', files=packlist),
)

PyErector()
